### ISSUE TITLE
Fatal Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by tanc** [BKWLD/nuxt-remote-asset-cache#7]
I'm just testing out this plugin but immediately hit the following fatal error:

```bash
 FATAL  Cannot find module 'babel-runtime/regenerator'                            
Require stack:
- /xxx/xxx/xxx/xxx/frontend/node_modules/nuxt-remote-asset-cache/dist/sync-assets.js 

  Require stack:
  - node_modules/nuxt-remote-asset-cache/dist/sync-assets.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
  at Function.resolve (internal/modules/cjs/helpers.js:80:19)
  at m (node_modules/jiti/dist/jiti.js:1:52899)
  at f (node_modules/jiti/dist/jiti.js:1:53712)
  at node_modules/nuxt-remote-asset-cache/dist/sync-assets.js:7:20
  at f (node_modules/jiti/dist/jiti.js:1:54601)
  at node_modules/nuxt-remote-asset-cache/nuxt/module.js:3:42
  at Resolver.f [as _require] (node_modules/jiti/dist/jiti.js:1:54601)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:182:38)
```

Nuxt version `2.15.3`

Removing this plugin allows yarn dev to work again.

**Comment by tanc** [comment]
Adding `babel-plugin-transform-runtime` as a dev dependency allowed it to run properly

**Comment by weotch** [comment]
Huh, I'll add that to the repo, thanks!

**Comment by weotch** [comment]
Oh, it already is added ... https://github.com/BKWLD/nuxt-remote-asset-cache/blob/master/package.json#L16 ... maybe I need to edit babel config so this ships with that already baked in...
